### PR TITLE
Change Cache-Control default max-age to one minute

### PR DESCRIPTION
**Pull request by lann**
The extremely long cache expiration doesn't match usage.

Also clean up a minor clippy lint.

### CODE REVIEW

**Comment by lann** [comment]
@technosophos FYI

**Comment by mikkelhegn** [comment]
Should this be a configuration in spin.toml?

**Comment by lann** [comment]
It is. Hence "default" 🙂

**Comment by mikkelhegn** [comment]
👯‍♂️ - It's Friday!!! (trying to come up with an excuse...)

**Review by mikkelhegn — APPROVED** [review]

**Pull request merged**
